In [26]:
class LR:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, X_train, y_train):
        num = 0
        den = 0
        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)
        
    def predict(self, X_test): 
        return self.m * X_test + self.b

In [11]:
import numpy as np 
import pandas as pd 

In [12]:
df = pd.read_csv('placement.csv')

In [13]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [14]:
X = df.iloc[:, 0].values
y = df.iloc[:, 1].values

In [15]:
X

array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
       6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94, 7.48, 7.28, 6.85,
       6.14, 6.19, 6.53, 7.28, 8.31, 5.42, 5.94, 7.15, 7.36, 8.1 , 6.96,
       6.35, 7.34, 6.87, 5.99, 5.9 , 8.62, 7.43, 9.38, 6.89, 5.95, 7.66,
       5.09, 7.87, 6.07, 5.84, 8.63, 8.87, 9.58, 9.26, 8.37, 6.47, 6.86,
       8.2 , 5.84, 6.6 , 6.92, 7.56, 5.61, 5.48, 6.34, 9.16, 7.36, 7.6 ,
       5.11, 6.51, 7.56, 7.3 , 5.79, 7.47, 7.78, 8.44, 6.85, 6.97, 6.94,
       8.99, 6.59, 7.18, 7.63, 6.1 , 5.58, 8.44, 4.26, 4.79, 7.61, 8.09,
       4.73, 6.42, 7.11, 6.22, 7.9 , 6.79, 5.83, 6.63, 7.11, 5.98, 7.69,
       6.61, 7.95, 6.71, 5.13, 7.05, 7.62, 6.66, 6.13, 6.33, 7.76, 7.77,
       8.18, 5.42, 8.58, 6.94, 5.84, 8.35, 9.04, 7.12, 7.4 , 7.39, 5.23,
       6.5 , 5.12, 5.1 , 6.06, 7.33, 5.91, 6.78, 7.93, 7.29, 6.68, 6.37,
       5.84, 6.05, 7.2 , 6.1 , 5.64, 7.14, 7.91, 7.19, 7.91, 6.76, 6.93,
       4.85, 6.17, 5.84, 6.07, 5.66, 7.57, 8.28, 6.

In [16]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [23]:
X_train.shape

(160,)

In [27]:
lr = LR()

In [28]:
lr.fit(X_train, y_train)

0.5579519734250721
-0.8961119222429152


In [29]:
X_test

array([8.58, 7.15, 5.88, 6.22, 4.57, 4.79, 5.32, 6.86, 8.35, 6.87, 8.94,
       7.9 , 6.93, 5.91, 7.32, 7.82, 5.09, 7.42, 6.94, 7.73, 6.19, 7.28,
       6.73, 7.2 , 8.21, 6.75, 7.87, 7.6 , 8.63, 5.12, 8.15, 7.36, 8.31,
       6.6 , 6.59, 7.47, 7.93, 6.29, 6.37, 6.47])

In [30]:
X_test[0]

8.58

In [31]:
lr.predict(X_test[0])

3.891116009744203

In [32]:
class SLR:
    def __init__(self): 
        self.m = None
        self.b = None

    def fit(self, X_train, y_train):
        num = 0
        den = 0
        xbar = X_train.mean()
        ybar = y_train.mean()
        for i in range(X_train.shape[0]): 
            num = num + ((X_train[i] - xbar) * (y_train[i] - ybar))
            den = den + ((X_train[i] - xbar) * (X_train[i] - xbar))

        self.m = num/den
        self.b = ybar - self.m * xbar
        print(self.m)
        print(self.b)

    def predict(self, X_test): 
        return self.m * X_test + self.b

In [33]:
slr = SLR()

In [35]:
slr.fit(X_train, y_train)

0.5579519734250721
-0.8961119222429152


In [36]:
slr.predict(X_test[0])

3.891116009744203

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [38]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [40]:
lr.fit(X_train, y_train)

ValueError: Expected 2D array, got 1D array instead:
array=[7.14 8.93 5.42 5.1  7.77 6.76 6.89 6.68 7.91 7.89 8.71 7.95 6.61 6.26
 6.53 6.42 5.11 6.09 6.93 7.04 5.94 6.05 5.83 5.95 9.31 5.58 7.88 6.13
 7.76 4.85 6.19 8.6  6.07 7.18 5.12 7.39 8.25 8.28 7.13 7.35 5.66 5.99
 8.01 7.14 6.34 6.89 5.42 6.47 7.69 7.4  7.28 5.95 7.38 6.93 8.99 7.36
 7.08 5.38 7.56 8.22 5.84 6.78 7.19 7.28 6.79 6.12 6.85 8.2  6.84 7.37
 6.22 6.61 5.23 7.21 6.85 6.19 7.3  6.17 5.89 8.09 7.11 4.26 6.94 5.98
 6.71 7.33 9.06 6.1  5.48 6.1  7.56 7.29 5.84 7.48 7.61 5.79 5.61 7.34
 9.38 7.91 6.94 7.94 8.31 6.96 6.93 7.11 8.44 8.18 6.66 8.44 7.12 6.3
 5.84 6.98 7.63 5.64 7.43 8.87 7.84 5.84 9.58 8.37 7.63 6.31 6.5  8.11
 6.07 4.73 7.3  6.51 7.28 6.92 6.35 8.62 7.05 9.26 6.33 6.22 6.94 5.13
 8.13 5.9  9.04 6.06 7.57 8.1  9.16 5.84 7.89 6.63 7.09 5.53 6.75 7.62
 6.97 7.66 6.14 7.78 7.25 8.65].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [41]:
df = pd.read_csv('placement.csv')

In [42]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [43]:
X = df.iloc[:,0]
y = df.iloc[:,1]

In [44]:
X

0      6.89
1      5.12
2      7.82
3      7.42
4      6.94
       ... 
195    6.93
196    5.89
197    7.21
198    7.63
199    6.22
Name: cgpa, Length: 200, dtype: float64

In [45]:
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ... 
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [50]:
X_train = X_train.values.reshape(-1,1)
X_train

array([[7.14],
       [8.93],
       [5.42],
       [5.1 ],
       [7.77],
       [6.76],
       [6.89],
       [6.68],
       [7.91],
       [7.89],
       [8.71],
       [7.95],
       [6.61],
       [6.26],
       [6.53],
       [6.42],
       [5.11],
       [6.09],
       [6.93],
       [7.04],
       [5.94],
       [6.05],
       [5.83],
       [5.95],
       [9.31],
       [5.58],
       [7.88],
       [6.13],
       [7.76],
       [4.85],
       [6.19],
       [8.6 ],
       [6.07],
       [7.18],
       [5.12],
       [7.39],
       [8.25],
       [8.28],
       [7.13],
       [7.35],
       [5.66],
       [5.99],
       [8.01],
       [7.14],
       [6.34],
       [6.89],
       [5.42],
       [6.47],
       [7.69],
       [7.4 ],
       [7.28],
       [5.95],
       [7.38],
       [6.93],
       [8.99],
       [7.36],
       [7.08],
       [5.38],
       [7.56],
       [8.22],
       [5.84],
       [6.78],
       [7.19],
       [7.28],
       [6.79],
       [6.12],
       [6.

In [51]:
y_train = y_train.values.reshape(-1,1)
y_train

array([[3.13],
       [3.91],
       [2.25],
       [2.3 ],
       [4.06],
       [3.18],
       [2.7 ],
       [2.49],
       [3.15],
       [2.99],
       [4.08],
       [4.14],
       [2.6 ],
       [2.44],
       [2.71],
       [2.72],
       [1.63],
       [2.31],
       [2.51],
       [3.5 ],
       [2.24],
       [2.58],
       [2.42],
       [2.54],
       [4.37],
       [2.17],
       [3.14],
       [2.19],
       [3.54],
       [1.54],
       [2.72],
       [3.98],
       [2.46],
       [3.  ],
       [1.98],
       [2.65],
       [3.75],
       [3.67],
       [2.93],
       [3.08],
       [2.21],
       [2.84],
       [3.76],
       [3.03],
       [2.09],
       [3.26],
       [2.16],
       [2.7 ],
       [3.83],
       [2.88],
       [3.16],
       [3.04],
       [3.13],
       [3.04],
       [4.6 ],
       [3.26],
       [2.85],
       [2.09],
       [3.31],
       [3.89],
       [1.87],
       [3.11],
       [2.4 ],
       [3.48],
       [3.08],
       [2.76],
       [2.

In [52]:
lr.fit(X_train, y_train)

LinearRegression()

In [56]:
y_pred = lr.predict(X_test.values.reshape(-1,1))

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [57]:
MAE = mean_absolute_error(y_test, y_pred)

In [58]:
MAE

0.2884710931878175

In [59]:
MSE = mean_squared_error(y_test, y_pred)

In [60]:
MSE

0.12129235313495527

In [61]:
r2 = r2_score(y_test, y_pred)

In [62]:
r2

0.780730147510384

In [63]:
RMSE = np.sqrt(mean_squared_error(y_test, y_pred))

In [64]:
RMSE

0.34827051717731616

In [65]:
new_df1 = pd.read_csv('placement.csv')

In [66]:
new_df1

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [67]:
new_df1['random_feature'] = np.random.random(200)


In [68]:
new_df1

cgpa  package  random_feature
0    6.89     3.26        0.528663
1    5.12     1.98        0.066149
2    7.82     3.25        0.218848
3    7.42     3.67        0.951117
4    6.94     3.57        0.021083
..    ...      ...             ...
195  6.93     2.46        0.467035
196  5.89     2.57        0.179380
197  7.21     3.24        0.885186
198  7.63     3.96        0.783408
199  6.22     2.33        0.613079

[200 rows x 3 columns]

In [69]:
new_df1 = new_df1[['cgpa', 'random_feature', 'package']]

In [70]:
new_df1

cgpa  random_feature  package
0    6.89        0.528663     3.26
1    5.12        0.066149     1.98
2    7.82        0.218848     3.25
3    7.42        0.951117     3.67
4    6.94        0.021083     3.57
..    ...             ...      ...
195  6.93        0.467035     2.46
196  5.89        0.179380     2.57
197  7.21        0.885186     3.24
198  7.63        0.783408     3.96
199  6.22        0.613079     2.33

[200 rows x 3 columns]

In [71]:
X1 = new_df1.iloc[:, 0:2]
y1 = new_df1.iloc[:,-1]

In [72]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.2, random_state=2)

In [73]:
lr1 = LinearRegression()

In [74]:
lr1.fit(X_train1, y_train1)

LinearRegression()

In [75]:
y_pred1 = lr1.predict(X_test1)

In [76]:
y_pred1

array([3.91706041, 3.13022353, 2.3502165 , 2.5847151 , 1.65194562,
       1.80651358, 2.04159504, 2.90177493, 3.75088241, 2.92322869,
       4.12422861, 3.47711437, 2.93800414, 2.40404265, 3.17218489,
       3.44294069, 1.9554423 , 3.27990178, 2.98190467, 3.4479961 ,
       2.59029727, 3.16906099, 2.83016375, 3.15925302, 3.69408837,
       2.87716646, 3.45437906, 3.37934907, 3.90095722, 1.9810689 ,
       3.612087  , 3.24166041, 3.73778183, 2.77520152, 2.7790405 ,
       3.25335944, 3.4866354 , 2.58855896, 2.68086101, 2.70550697])

In [78]:
y_test1

112    4.10
29     3.49
182    2.08
199    2.33
193    1.94
85     1.48
10     1.86
54     3.09
115    4.21
35     2.87
12     3.65
92     4.00
13     2.89
126    2.60
174    2.99
2      3.25
44     1.86
3      3.67
113    2.37
14     3.42
23     2.48
25     3.65
6      2.60
134    2.83
165    4.08
173    2.56
45     3.58
65     3.81
48     4.09
122    2.01
178    3.63
64     2.92
9      3.51
57     1.94
78     2.21
71     3.34
128    3.34
176    3.23
131    2.01
53     2.61
Name: package, dtype: float64

In [81]:
print('MAE', mean_absolute_error(y_test1, y_pred1))
print('MSE', mean_squared_error(y_test1, y_pred1))
print('RMSE', np.sqrt(mean_squared_error(y_test1, y_pred1)))
print('R2 Score', r2_score(y_test1, y_pred1))
r21 = r2_score(y_test1, y_pred1)

MAE 0.28866709334975066
MSE 0.12217989869850569
RMSE 0.34954241330417357
R2 Score 0.7791256606670875


In [82]:
1 - ((1-r2)*(40-1)/(40-1-2))

0.7688777230514858